Added string to overlay text converter node
teamspatzenhirn/overlay_rviz_plugins pull request #18
Opened 2023-05-09 13:55 UTC by horverno

A small converter node related to https://github.com/teamspatzenhirn/rviz_2d_overlay_plugins/issues/17

2023-05-12 09:11 UTC, ottojo requested changes
Thanks for the contribution!

Some of the code style and formatting doesn't match what we use internally, but since this already is a mix of JSK sources and our own, i don't really mind. @authaldo feel free to review if you think otherwise.

I will test the functionality later or over the weekend, and will prepare a release after merging :+1:

2023-05-12 09:11 UTC, ottojo commented on rviz_2d_overlay_plugins/src/string_to_overlay_text.cpp
> +        //RCLCPP_INFO_STREAM(this->get_logger(), "Str: " << st_msg.data << " ");
```suggestion
```

2023-05-12 09:11 UTC, ottojo commented on rviz_2d_overlay_plugins/launch/string_to_overlay_text_example.launch.py
I think it would be more beneficial to put this in the documentation, to make it easy for users to copy-paste into their own launch file.

If you could put this, together with the notes at the top of string_to_overlay_text.cpp and the build instructions you added into [the readme inside the plugin package](https://github.com/teamspatzenhirn/rviz_2d_overlay_plugins/blob/main/rviz_2d_overlay_plugins/README.md), that would be great! That readme is also what ends up on the hosted docs linked on the ros index: https://docs.ros.org/en/rolling/p/rviz_2d_overlay_plugins/generated/doxygen/html/

2023-05-12 11:43 UTC, horverno commented on rviz_2d_overlay_plugins/launch/string_to_overlay_text_example.launch.py
Agreed, I added a small description into the readme inside the plugin package:
https://github.com/teamspatzenhirn/rviz_2d_overlay_plugins/pull/18/commits/980e4d9dbdb46fd048a27536b1efae2b9c6967f8

2023-05-12 11:48 UTC, authaldo commented on rviz_2d_overlay_plugins/README.md
> +A simple coverter node (`rviz2d_from_string_node`) is provided which can covert `std_msgs/msg/String` to `rviz_2d_overlay_msgs/msg/OverlayText`. The working principle is simple, it subscribes to a `S
```suggestion
A simple coverter node (`rviz2d_from_string_node`) is provided which can covert `std_msgs/msg/String` to `rviz_2d_overlay_msgs/msg/OverlayText`. The working principle is simple, it subscribes to a `String` topic, publishes the content as an `OverlayText` and the other properties can be set from ROS parameters or by overtaking it in RViz2.
```

2023-05-12 11:53 UTC, authaldo commented
Just out of curiosity: What's the benefit of adding the foreground color in the node? Shouldn't there already be an option to override it directly in the rviz plugin?

2023-05-12 12:09 UTC, horverno commented
> Just out of curiosity: What's the benefit of adding the foreground color in the node? Shouldn't there already be an option to override it directly in the rviz plugin?

You are right, it can be overridden in rviz, the only small benefit to do this, is the possibility display it instantly, because it is not transparent by default.

2023-05-17 17:43 UTC, ottojo requested changes
sorry for the delay, i verified the basic functionality just now!

please remove `rviz_2d_overlay_plugins/launch/string_to_overlay_text_example.launch.py` and the corresponding changes in `rviz_2d_overlay_plugins/package.xml` and `rviz_2d_overlay_plugins/CMakeLists.txt`, that launch file on its own does nothing more than `ros2 run rviz_2d_overlay_plugins string_to_overlay_text`... It will just get out of sync with the readme and cause confusion...

once thats done, it's good to go :+1:

2023-05-18 10:22 UTC, ottojo approved these changes

2023-05-18 10:22 UTC, merged

2023-05-18 10:39 UTC, ottojo commented
Thanks for your contribution! I prepared binary releases for humble and rolling, those should be available once the next sync is out after those MRs are merged: https://github.com/ros/rosdistro/pull/37259 https://github.com/ros/rosdistro/pull/37260