WIP: Improved alignment
teamspatzenhirn/overlay_rviz_plugins pull request #6
Opened 2022-09-18 19:26 UTC by authaldo

Fixes #2

2022-09-18 20:00 UTC, ottojo commented on overlay_rviz_msgs/msg/OverlayText.msg
> +uint8 vertical_alignment # applied to overlay and parent frame
```suggestion
# Alignment of the overlay withing RVIZ
uint8 horizontal_alignment # one of LEFT, CENTER, RIGHT
uint8 vertical_alignment # one of TOP, CENTER, BOTTOM
```

2022-09-18 20:01 UTC, ottojo reviewed
sieht alright aus, werde das morgen noch ausprobieren :+1:

2022-09-18 20:07 UTC, authaldo commented on overlay_rviz_msgs/msg/OverlayText.msg
> +uint8 vertical_alignment # applied to overlay and parent frame
Finde den Vorschlag gut, fehlt nur irgendwie noch, dass sich der Reference Point für die horizontalen / vertikalen Distanzen mit dem Alignment ändert

2022-09-19 09:45 UTC, ottojo requested changes
Funktioniert wunderbar!

Mir ist gerade noch aufgefallen dass es unangenehm viele konstanten für die alignment optionen gibt: Message konstanten, constexpr in overlay_rviz_plugins/src/overlay_text_display.cpp, enum mit expliziten werten in overlay_rviz_plugins/include/overlay_utils.hpp. Könnte man da nicht überall die konstanten aus der message definition nutzen? dann könnte man vmtl auch ein paar switch/case mit static_cast ersetzen

2022-09-19 09:46 UTC, ottojo commented on overlay_rviz_msgs/msg/OverlayText.msg
> +uint8 vertical_alignment # applied to overlay and parent frame
was bedeutet das?

2022-09-19 20:04 UTC, authaldo commented on overlay_rviz_msgs/msg/OverlayText.msg
> +uint8 vertical_alignment # applied to overlay and parent frame
Die Werte beziehen sich immer auf die Distanz zum Referenzpunkt:
Ist der bspw. horizontal left und vertikal top, und beide Distanzen null, so ist das Overlay so platziert, dass die linke obere Ecke des Overlays sich auf der linken oberen Ecke des RViz Fensters befindet. Erhöht man die horizontale Distanz, so bewegt sich das Overlay nach rechts (weg vom Referenzpunkt).
Ist das Alignment horizontal right und vertikal top, und beide Distanzen null, so ist das Overlay jetzt so platziert, dass die rechte obere Ecke des Overlays sich auf der rechten oberen Ecke des RViz Fensters befindet. Erhöht man nun die Distanz, so wird nach links verschoben (wieder vom Referenzpunkt weg). 
Center tanzt aus der Reihe und schiebt halt auch nach links.

Ich wollte das nicht mehr als left und top haben, weil diese Distanzen implizit immer von der linken oberen Ecke des Overlays ausgegangen sind. Damit hätte man für den rechts oben Fall manuell die width abziehen müssen. 
Wenn ich das gerade nochmal betrachte macht es aber vermutlich mehr Sinn die Richtung immer beizubehalten, d.h. im Fall rechts oben dann auch negative Distanzen um nach links zu schieben.
Die Referenz am Overlay würde ich aber trotzdem als Distanz interpretieren. Heißt, wenn ich rechts aligne, dann wird jeweils die Distanz zwischen den beiden rechten Kanten genommen. Auf diese Weise muss man sich nicht selber noch Gedanken mit der Width machen. 

Was hälst du davon?

2022-09-19 20:05 UTC, authaldo commented
Den Punkt mit den Konstanten werde ich mir nochmal anschauen 👍

2022-09-20 09:42 UTC, ottojo commented on overlay_rviz_msgs/msg/OverlayText.msg
> +uint8 vertical_alignment # applied to overlay and parent frame
also ich würde das so machen dass positive distanz immer nach innen verschiebt (bei center halt nach rechts/unten)

Ich glaube so ist das momentan schon?

Würde dann nur noch die doku beim distance wert anpassen

2022-09-20 09:45 UTC, ottojo commented on overlay_rviz_msgs/msg/OverlayText.msg
> +uint8 vertical_alignment # applied to overlay and parent frame
```suggestion
# Position: Positive values move the overlay towards the center of the window,
#  for center alignment positive vlues move the overlay towards the bottom right
int32 horizontal_distance # Horizontal distance from left/right border, depending on alignment
int32 vertical_distance # Vertical distance between from top/bottom border, depending on alignment

# Alignment of the overlay withing RVIZ
uint8 horizontal_alignment # one of LEFT, CENTER, RIGHT
uint8 vertical_alignment # one of TOP, CENTER, BOTTOM
```

2022-09-21 20:18 UTC, ottojo commented on overlay_rviz_plugins/include/overlay_utils.hpp
> +        LEFT = 0, RIGHT = 1, CENTER = 2
plz use message constants

2022-09-21 20:24 UTC, ottojo approved these changes

2022-09-21 20:26 UTC, merged